### ISSUE TITLE
libnetcdf.so dependency

### ISSUE THREAD

**Issue by jswanljung** [conda-forge/pyferret-feedstock#11]
I got the following error when running pyferret (on Ubuntu): 

``` shell
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/jswan/anaconda2/pkgs/pyferret-7.0.0-py27_4/lib/python2.7/site-packages/pyferret/__init__.py", line 42, in <module>
    import libpyferret
ImportError: libnetcdf.so.11: cannot open shared object file: No such file or directory
```

Then I updated libnetcdf, hdf5 and esmf using conda, after which pyferret runs just fine! I'm thinking maybe some dependency is missing from the pyferret recipe.

**Comment by ocefpaf** [comment]
`libnetcdf.so.11` comes from `libnetcdf` and `conda-forge`'s version do ship the proper shared library via `netcdf-fortran` as you can see  [here](https://github.com/conda-forge/pyferret-feedstock/blob/master/recipe/meta.yaml#L22) and [here](https://github.com/conda-forge/netcdf-fortran-feedstock/blob/master/recipe/meta.yaml#L21).

The problem is that conda might be mixing packages versions from the default channel. To avoid that make sure you have the latest `conda` installed and add the `conda-forge` channel on top of `defaults` in your `.condarc`. That may help the solver get the proper version for `libnetcdf`.

A quick way to debug this is to install in a controlled env like this:

``` shell
conda create -n TEST pyferret --yes --channel conda-forge
source activate TEST
python -c "import pyferret; print(dir(pyferret))"
```

If that works it means you got the right stack of dependencies. If not, you should try updating your `conda` and changing the channel preference as I said above.

**Comment by jswanljung** [comment]
Yes, testing it in a controlled environment worked fine, and anyway it worked fine in my default environment too after I updated some things manually. Thanks.

**Comment by ocefpaf** [comment]
Sorry we cannot address that on our side. But at least now you now what to look for and force install it :grimacing: (The conda-forge version of `libnetcdf`.)

**Comment by jswanljung** [comment]
Yes, and this was in any case painless compared to getting the official pyferret binary working on my system. Thanks for your work on this and for your quick response.
